---

- name: Replace values /var/www/html/laravelapp/.env file
  lineinfile:
    path: /var/www/html/laravelapp/.env
    regexp: '^{{item.key}}='
    line: "{{item.key}}={{item.value}}"
  with_dict: {DB_CONNECTION: mysql, DB_HOST: 127.0.0.1, DB_PORT: 3306, DB_DATABASE: LaravelApp, DB_USERNAME: root, DB_PASSWORD: root}      

- name: Seed the DB
  shell: php artisan migrate --seed
  args:
    chdir: /var/www/html/laravelapp/